### ISSUE TITLE
Cannot move around after exiting help view and keybindings suggestion

### ISSUE THREAD

**Issue by BachoSeven** [dundee/gdu#1]
Hi! I imagine this is very much still in testing, but I tried your package from the AUR and noticed that:
- after exiting the newly added help panel one cannot move around anymore; i.e. navigation is broken.
- since you implemented some vi-like bindings, such as `j`, `k`, `g` and `G`; you could also use `h` and `l` as alternatives to `Enter` and the `/..` button to navigate up and down folders.

**Comment by dundee** [comment]
Thanks for your report!

**Comment by dundee** [comment]
`h` and `l` keys added, thanks for suggestion!
