### ISSUE TITLE
gdu dies scanning large directory

### ISSUE THREAD

**Issue by daniejstriata** [dundee/gdu#102]
I was scanning a location with many, many small files. It got killed. Is there anything I can do to help track down the problem?
![image](https://user-images.githubusercontent.com/13314239/140163960-ba2b2d67-bd01-4ce7-b141-73243e061173.png)

When I run ncdu on the same location it seems to soldier on using 1GB or RAM
![image](https://user-images.githubusercontent.com/13314239/140163438-689e4af5-3bd9-4535-870d-6c2e45d5fa25.png)

I tried with dust too, it also got killed when it started using over 8GB of RAM.

```
---------------------------Server Information---------------------------
 ____^____     
 |\  |  /|     os     CentOS Linux release 7.9.2009 (Core)
 | \ | / |     host   r5a.large
<---- ---->    kernel 5.4.125-200.el7.x86_64
 | / | \ |     uptime 122d 17h 7m
 |/__|__\|     pkgs   746
     v         memory 10508M / 15757M
```

**Comment by daniejstriata** [comment]
ncdu is now using 4GB and still going.
![image](https://user-images.githubusercontent.com/13314239/140180593-83caa02f-31d6-46e7-8356-ef8ac3b8abe7.png)
![image](https://user-images.githubusercontent.com/13314239/140180623-06652164-f425-481d-99c7-395044fbb90e.png)

**Comment by dundee** [comment]
This can happen. When the system runs out of memory, OOM Killer will kill gdu. The memory consumption of gdu will always be higher than of ncdu, because Golang has some overhead in comparison to plain C.

The memory consumption of gdu could still be improved a bit though.

**Comment by daniejstriata** [comment]
Is there not something I can do to help? Run it with debugging turned on or something?

**Comment by dundee** [comment]
You can turn on profiler - https://pkg.go.dev/net/http/pprof and see what consumes the memory.

**Comment by dundee** [comment]
I probably should add one clarification first: this behaviour is expected. When some process consumes too much memory and the operating system runs out of it, the process is terminated by the system. So it's not a bug in gdu, it's a consequence of using a lot of memory when scanning huge filesystems. 

We probably could lower this usage a bit, but I guess not by a large margin. It will always be using more memory than tool written in pure C.
