### ISSUE TITLE
How build and upload all platform bins to the Github release page?

### ISSUE THREAD

**Issue by zhangsean** [dundee/gdu#105]
How build and upload all platform bins to the Github release page?
Is there any easy and quick method? for example, to use the Github Actions?

By the way, I create a project [gns](https://github.com/zhangsean/gns), it's a network scan tool by Go.
Please give me some suggestions to improve it.

**Comment by dundee** [comment]
I don't do this personally yet, but it looks like it's possible:
https://trstringer.com/github-actions-create-release-upload-artifacts/
or 
https://github.com/softprops/action-gh-release

**Comment by dundee** [comment]
It looks like a nice project! 

I would:

* fix missing dependencies in go.sum

```
go: github.com/cheggaaa/pb@v1.0.29: missing go.sum entry; to add it:
	go mod download github.com/cheggaaa/pb
```	

* rename module to fullpath

```
go: downloading github.com/zhangsean/gns v0.8.1
go install: github.com/zhangsean/gns@latest: github.com/zhangsean/gns@v0.8.1: parsing go.mod:
	module declares its path as: gns
	        but was required as: github.com/zhangsean/gns
```

* add install instructions etc.
