### ISSUE TITLE
-x missing for OSX

### ISSUE THREAD

**Issue by oderwat** [dundee/gdu#107]
I came here and found ##106, but I miss -x on OSX (a lot!). What is the problem there? I think `mount` with `-l` or even without parameters could deliver the needed information. I may be able to help with the implementation but wanted to ask about the reason why it is missing before I look at the code.

**Comment by dundee** [comment]
The reason is that I don't have OSX myself, so I am unable to implenent it and test it. It would be great, If you did it!
