### ISSUE TITLE
How to display International System of Units values?

### ISSUE THREAD

**Issue by parabolapersuader** [dundee/gdu#117]
It should have been the default. Instead, I can't even find a way to switch from `GiB` to `GB`.

**Comment by dundee** [comment]
Thanks for suggestion!

**Comment by parabolapersuader** [comment]
Excellent!

Could you make it honor $BLOCKSIZE and / or $BLOCK_SIZE ?

**Comment by dundee** [comment]
Good idea

> Excellent!
> 
> Could you make it honor $BLOCKSIZE and / or $BLOCK_SIZE ?

Nice idea! I have created #120 for this.
