### ISSUE TITLE
The directory calculation menu freezes

### ISSUE THREAD

**Issue by BlitGaming** [dundee/gdu#122]
This happens if you hold down the **r** key to recalculate the current directory. The calculation menu freezes and does not update, only the **q** key works to exit the gdu. There is no such problem in ncdu, but the interface is not beautiful and the calculation speed is much slower than that of gdu, so I would like to fix this problem.

My Neofetch:
```bash
                   -`                    blitdev@inspiron 
                  .o+`                   ---------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: Inspiron N5110 
               `+oooooo:                 Kernel: 5.16.2-zen1-1-zen 
               -+oooooo+:                Uptime: 16 mins 
             `/:-:++oooo+:               Packages: 1631 (pacman) 
            `/++++/+++++++:              Shell: fish 3.3.1 
           `/++++++++++++++:             Resolution: 1366x768 
          `/+++ooooooooooooo/`           DE: Plasma 5.23.5 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         Theme: Breeze Light [Plasma], Breeze [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: konsole 
     /ossssssss/        +ssssooo/-       Terminal Font: Hack 10 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-2670QM (8) @ 3.100GHz 
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce GT 525M 
 `++:.                           `-/+/   GPU: Intel 2nd Generation Core Processor Family 
 .`                                 `/   Memory: 2304MiB / 7853MiB 

```

**Comment by dundee** [comment]
What version of gdu are you using? I am not able to replicate this issue with the latest 5.12.1.

**Comment by BlitGaming** [comment]
> What version of gdu are you using? I am not able to replicate this issue with the latest 5.12.1.

I'm use 5.12.1

**Comment by BlitGaming** [comment]
This bug is also present in the latest version of the git branch.

**Comment by dundee** [comment]
I am able to reproduce it on small directories when holding `r` for a while.

**Comment by daniejstriata** [comment]
When I was scanning a large directory I pressed and held r. When I then pressed q, while gdu was scanning, it took a couple of seconds (approx 10) to get back to the shell.

I also noticed that directories are sorted differently if they are the same size with each rescan.
