### ISSUE TITLE
Provide statically linked gdu

### ISSUE THREAD

**Issue by Zabrane** [dundee/gdu#133]
Hi @dundee 
What needs to be done to statically compile `gdu` ?
I'd like to use it on `RedHat7` which has an old libc.

**Comment by daniejstriata** [comment]
Hi, The provided RPM runs on RHEL 6+

**Comment by dundee** [comment]
@Zabrane Does this work for you? I am wondering if I should include some static binaries in the releases as well.

**Comment by Zabrane** [comment]
@dundee musl static versions would be awesome.
The problem with RPMs is that I can't install them internally (they have to be signed by trusted entity, ...).

**Comment by daniejstriata** [comment]
@Zabrane you could use the provided SRC RPM to build your own package and distribute it to your environment.

**Comment by dundee** [comment]
Static binary added to the latest release.
