### ISSUE TITLE
Use the current directory when there's no argument

### ISSUE THREAD

**Issue by ouuan** [dundee/gdu#14]
I'd like `gdu` to behave like `gdu .`

About the current behavior, there are two possible options:
1. This behavior can be toggled in the config.
2. The current behavior when there's no argument can be moved to a command-line option.

**Comment by dundee** [comment]
Why do you think it's better than current behaviour? 

You can show usage of current dir with just one extra letter.

**Comment by ouuan** [comment]
> Why do you think it's better than current behaviour?
> 
> You can show usage of current dir with just one extra letter.

Actually it's twice letters, if I'm using `alias du=gdu` and count the space. If the current behaviour is an option, I can use `alias df='gdu --some-option'`.

Anyway, I'm requesting the common behaviour of `ncdu` and `ls` etc.

**Comment by dundee** [comment]
That makes sence. I will change it.
