### ISSUE TITLE
Feature: Export JSON from interactive mode

### ISSUE THREAD

**Issue by dufferzafar** [dundee/gdu#141]
Currently, `export` mode needs to be run via the CLI using `-o` flag.

It would be great if we could export the JSON once we already have the interactive UI running.

It could also allow exporting the highlighted folder rather than the entire tree.

**Comment by kadogo** [comment]
Hello, I just discovered gdu and I wanted to make an issue for that.

I noticed we can "refresh" after we load an export file. It would make sense to be able to save it in the same file or in a new file. Maybe a new file is better, and it would avoid trouble about rewriting information on the file we are reading.
