### ISSUE TITLE
feature: (sub)sort entries alphabetically, if their size is equal

### ISSUE THREAD

**Issue by leapfog** [dundee/gdu#143]
I hit this twice: I re-scanned a folder that had several subfolders. And at another time I used gdu to delete folders.

In both situations, existing folders with equal size randomly changed their place in the listing. This can be triggered with:

> $ mkdir -p testdir/{0..9}
> gdu testdir

and than pressing "r" to re-scan.

Suggestion: sort folders with equal size alphabetically, that way the list would become static. As far as I can see, files with equal size are already sorted. At least I can only trigger it with folders.

**Comment by daniejstriata** [comment]
I've seen this happen myself
