### ISSUE TITLE
Feature: Add flag for showing sizes as bytes

### ISSUE THREAD

**Issue by ev-dev** [dundee/gdu#147]
Hey really awesome work, gdu has been one of my go-to system info tools for a while now!

I often use gdu in non-interactive mode to quickly get file/dir sizes using `gdu -nps`, and it is super useful that gdu automatically converts sizes to the most appropriate prefix (KiB/MiB/GiB or kB/MB/GB using --si flag). But especially when scripting, I wish I could also have the option to output raw bytes to make it easier to do math/compare size values.

At present I have been using pretty hacky shell function to use gdu's --out-file flag combined with a weird and complicated jq statement on the output json but it would be really useful to be able to print raw byte sizes to the console with gdu itself. Admittedly it seems less useful in interactive mode, but I think still worth the effort for non-interactive use.

Any thoughts?

**Comment by dundee** [comment]
Hi, yes, it makes sense to add it to non-interactive mode. I will try to push it into the next release.

**Comment by ev-dev** [comment]
Hey thanks for the response glad you agree with the use case. I don't think I'm fluent enough in go to take a stab at it myself, but out of curiosity I might give it an hour of my best effort over the weekend and see how it goes. Certiainly looks like a pretty well-organized codebase so maybe implementing for stdout only won't be too complicated.

How would you prefer the usage design of a show raw bytes flag? It could be added as another boolean flag, but I'm not sure if that would then require some arg validation against coexisting with `--si` flag considering they would technically conflict in principle (but validation might be unnecessary for first implementation).

Another idea could be to introduce a `--size-format <format>` flag with possible values like `binary|decimal|raw` which would then consolidate this feature with the --si option. Seems like it would be a more significant change to gdu usage (would break scripts that use --si) but that might not a big deal to most users.

**Comment by ev-dev** [comment]
Nevermind, I guess a `--size-format <format>`  flag could still coexist with `--si` I'm probably overthinking it 🙃

**Comment by dundee** [comment]
I think we can just go with `-b | --bytes` to show the raw number of bytes it consumes. I would check if both `--si` and `--bytes` are given and print an error if so. What do you think?

**Comment by shanghungshih** [comment]
Hi @dundee ,
I'm using v5.23.0, but I can't find `-b` or `--bytes` option.
```
Version:         v5.23.0
Built time:      Sat Apr  8 11:40:43 PM CEST 2023
Built user:      dundee
```

```
Pretty fast disk usage analyzer written in Go.

Gdu is intended primarily for SSD disks where it can fully utilize parallel processing.
However HDDs work as well, but the performance gain is not so huge.

Usage:
  gdu [directory_to_scan] [flags]

Flags:
      --config-file string            Read config from file (default is $HOME/.gdu.yaml)
  -g, --const-gc                      Enable memory garbage collection during analysis with constant level set by GOGC
      --enable-profiling              Enable collection of profiling data and provide it on http://localhost:6060/debug/pprof/
  -L, --follow-symlinks               Follow symlinks for files, i.e. show the size of the file to which symlink points to (symlinks to directories are not followed)
  -h, --help                          help for gdu
  -i, --ignore-dirs strings           Absolute paths to ignore (separated by comma) (default [/proc,/dev,/sys,/run])
  -I, --ignore-dirs-pattern strings   Absolute path patterns to ignore (separated by comma)
  -X, --ignore-from string            Read absolute path patterns to ignore from file
  -f, --input-file string             Import analysis from JSON file
  -l, --log-file string               Path to a logfile (default "/dev/null")
  -m, --max-cores int                 Set max cores that GDU will use. 48 cores available (default 48)
  -c, --no-color                      Do not use colorized output
  -x, --no-cross                      Do not cross filesystem boundaries
  -H, --no-hidden                     Ignore hidden directories (beginning with dot)
      --no-mouse                      Do not use mouse
      --no-prefix                     Show sizes as raw numbers without any prefixes (SI or binary) in non-interactive mode
  -p, --no-progress                   Do not show progress in non-interactive mode
  -n, --non-interactive               Do not run in interactive mode
  -o, --output-file string            Export all info into file as JSON
  -a, --show-apparent-size            Show apparent size
  -d, --show-disks                    Show all mounted disks
  -B, --show-relative-size            Show relative size
      --si                            Show sizes with decimal SI prefixes (kB, MB, GB) instead of binary prefixes (KiB, MiB, GiB)
  -s, --summarize                     Show only a total in non-interactive mode
  -v, --version                       Print version
      --write-config                  Write current configuration to file (default is $HOME/.gdu.yaml)
```

**Comment by dundee** [comment]
Hi @shanghungshih,
the option is called `--no-prefix`.

**Comment by shanghungshih** [comment]
Thanks for the quick response! It works like a charm.
