### ISSUE TITLE
Feature: Sort by number in name natually

### ISSUE THREAD

**Issue by wwhio** [dundee/gdu#154]
Hi. Thank you for your nice work. I think it will be nice to have an additional feature. When we sort files by name, gdu will sort files with number natually. 

For example, when we sort by name, we get the following result currently.

```
asserts.zip
chapter1.txt
chapter10.txt
chapter11.txt
chapter2.txt
chapter20.txt
chapter3.txt
image1.jpg
image10.jpg
image2.jpg
image3.jpg
```

I expect to have sorting by name with number natually. For example,

```
assert.zip
chapter1.txt
chapter2.txt
chapter3.txt
chapter10.txt
chapter11.txt
chapter20.txt
image1.jpg
image2.jpg
image3.jpg
image10.jpg
```

I think it will be nice to have.

May be helpful : https://github.com/maruel/natural

**Comment by dundee** [comment]
Hi, nice idea! I will add it to the next release.
