### ISSUE TITLE
How can I use ctrl-n for down arrow and ctrl-p for up arrow?

### ISSUE THREAD

**Issue by avatar-lavventura** [dundee/gdu#155]
Is it possible to use `ctrl-n` for down arrow and `ctrl-p` for up arrow? If yes, how can I use it?

**Comment by dundee** [comment]
Gdu currently uses vim-like keyboard shortcuts. `j` for down arrow and `k` for up arrow.

**Comment by avatar-lavventura** [comment]
Is it possible to change those keybinding like into emacs-like keyboard shurtcuts?

**Comment by dundee** [comment]
Currently unfortunately not.

**Comment by avatar-lavventura** [comment]
@dundee Thanks anyway :-)
