### ISSUE TITLE
"Version: development" when built from AUR

### ISSUE THREAD

**Issue by ouuan** [dundee/gdu#16]
A possible solution:

1. Use [`git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'`](https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git) to get the version number. I'm not sure how to do this in Go, though.
2. Show only `vX.Y.Z` if the result is `vX.Y.Z.r0.gxxxxxxx`, otherwise show the whole result.
3. You need to provide a source with a part of the `.git` directory. You can refer to [this](https://github.com/cpeditor/cpeditor/blob/6a318d39d85225910320162c443c64ed87be93f5/.github/workflows/release.yml#L159-L164).

Another possible solution: Make releases on another branch, where the version numbers are hardcoded.

However, I think it's good to have the commit hash in the version info of the development version.

**Comment by dundee** [comment]
Fixed in https://aur.archlinux.org/cgit/aur.git/commit/?h=gdu&id=92516da6393f261e3cf4b08bc25b842f98b57586

Thanks for your report!
