### ISSUE TITLE
gdu 5.13.2-1 crashes if deleting files fast

### ISSUE THREAD

**Issue by oxou** [dundee/gdu#160]
I know I'm reporting a problem for a version of the software that's older compared to the latest version **5.15.0** as of writing.  But because I was not able to reproduce the problem again, I'm writing it here anyways.  I looked up the Issues both Open and Closed sections and couldn't find a crash report similar to this, or maybe I've missed it...

Either way, here's the crash:

```
panic: interface conversion: interface is nil, not fs.Item [recovered]
        panic: interface conversion: interface is nil, not fs.Item

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
        github.com/rivo/tview/application.go:243 +0x4d
panic({0x83a460, 0xc0006113e0})
        runtime/panic.go:1038 +0x215
github.com/dundee/gdu/v5/tui.(*UI).handleDelete(0xc0000ea9a0, 0xe9)
        github.com/dundee/gdu/v5/tui/keys.go:192 +0x9a
github.com/dundee/gdu/v5/tui.(*UI).keyPressed(0xc0000ea9a0, 0xc0000331a0)
        github.com/dundee/gdu/v5/tui/keys.go:103 +0x9d0
github.com/rivo/tview.(*Application).Run(0xc0001a6000)
        github.com/rivo/tview/application.go:318 +0x782
github.com/dundee/gdu/v5/tui.(*UI).StartUILoop(0xc00010bd60)
        github.com/dundee/gdu/v5/tui/tui.go:173 +0x22
github.com/dundee/gdu/v5/cmd/gdu/app.(*App).Run(0xc00010bd60)
        github.com/dundee/gdu/v5/cmd/gdu/app/app.go:145 +0x391
main.runE(0xbc4a00, {0xc4fc10, 0x0, 0x0})
        github.com/dundee/gdu/v5/cmd/gdu/main.go:101 +0x418
github.com/spf13/cobra.(*Command).execute(0xbc4a00, {0xc0000981e0, 0x0, 0x0})
        github.com/spf13/cobra/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xbc4a00)
        github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra/command.go:902
main.main()
        github.com/dundee/gdu/v5/cmd/gdu/main.go:105 +0x25
```

This error occured on Linux-Ubuntu-Server-22.04.1.  I was in `/usr/share/doc/` and was removing a couple of files through `gdu` by holding down the <kbd>Delete</kbd> key.  After the last file was deleted, gdu crashed with the report above.  I have tried other directories as a test and could not reproduce the issue anymore...  Perhaps the issue is still present in the latest version?  I've tried doing the tests in the latest build but couldn't reproduce it.

If this problem has already been encountered by someone else, then please mark this as a duplicate and close this issue.

**Comment by dundee** [comment]
@oxou I was not able to reproduce it, but I think I have found the proper place and way how to fix this.
Thanks for the report!
