### ISSUE TITLE
-c by default

### ISSUE THREAD

**Issue by stevensko** [dundee/gdu#166]
Please add an option for no color by default

**Comment by dundee** [comment]
Added option to use configuration file in https://github.com/dundee/gdu/commit/22398bb067acb93e2f8e630abe9d4b8b7d0a165b.

So you can now run: `echo "no-color: true" > ~/.gdu.yaml` and you will have gdu without colors.

**Comment by daniejstriata** [comment]
@dundee Can the config go into .config directory?

**Comment by Ved-un** [comment]
@dundee
Why do I get the message that there is no such flag?

![flameshot_259](https://user-images.githubusercontent.com/48730277/190653308-d3a07f09-e788-4464-b7f7-3c5e2417120c.png)

**Comment by dundee** [comment]
Oh, my bad. I refactored it to not use viper lib and forgot to add this flag manually.

**Comment by dundee** [comment]
Fixed in https://github.com/dundee/gdu/commit/3b55796fbcb7d1a45f1cc3e6750645751268c063
