### ISSUE TITLE
v5.16.0 - extremely slow UI - suspect "initial mouse support"

### ISSUE THREAD

**Issue by daniejstriata** [dundee/gdu#167]
On some of the hosts I installed gdu 5.16 on, the UI is extremely slow.  I'm trying to replicate this but seems to fix itself when I log out and log back in to the host.

When starting gdu I see a blank screen for a couple of seconds before the UI pops up and it scans the current location. When in gdu, scrolling up and down with the keyboard is extremely delayed.

Another thing I noticed since I changed my primary driver to Windows 11 is that the UI flashes each time I scroll up or down. ncdu does not flash updates when scrolling through the location content. This also did not happen when I used Linux. It must be something that Windows Terminal is doing different.

https://user-images.githubusercontent.com/13314239/189061326-c9003e38-17e1-4222-b33e-731616f6b5cb.mp4

I'm using Windows terminal 1.14.

**Comment by daniejstriata** [comment]
I'm not able to replicate the slowness in some sessions. Usually after logging out and back in gdu works like normal.

**Comment by dundee** [comment]
Let's add option to disable the mouse support and compare running gdu with that.

**Comment by rashil2000** [comment]
I can't reproduce the slowness, but yes the constant redrawing of the terminal on any action is quite jarring. I suspect it has something to do with the curses Go backend that gdu uses.

**Comment by daniejstriata** [comment]
can't replicate
