### ISSUE TITLE
Highlight color does not look great with certain terminal themes

### ISSUE THREAD

**Issue by kidonng** [dundee/gdu#168]
I'm using the [Tokyo Night](https://github.com/folke/tokyonight.nvim) theme in my terminal and the highlight color behaves poorly both in dark and light themes:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/44045911/189167349-73de3b42-88ae-4faf-9aa7-160b2c7dd703.png">

<img width="690" alt="image" src="https://user-images.githubusercontent.com/44045911/189167377-9b653c47-5b05-4840-a797-691cc1ad9e0f.png">

Other UI elements looks about right. Should I blame the theme, or is this something that can be improved?

I noticed the colors do change a bit outside of the test environment shown above, but I'm not sure what caused this (I have `$LS_COLORS` set, if it's worth mentioning), there doesn't seem to be a way to configure it either (except `--no-color`).

<img width="424" alt="image" src="https://user-images.githubusercontent.com/44045911/189168820-35284625-2d8f-41be-b070-4488dd51d113.png">

**Comment by Ved-un** [comment]
I have the same problem, although the theme is different...

![flameshot_252](https://user-images.githubusercontent.com/48730277/189367759-7151e713-5e7e-4cbe-984a-6f30102b8bfe.png)

**Comment by dundee** [comment]
Hi, I have added possibility to change color of the selected row in the configuration file.
