### ISSUE TITLE
gdu on Windows is not working

### ISSUE THREAD

**Issue by xd-mau5** [dundee/gdu#171]
With the lastest 5.16.0  and 5.17.0 gdu doesn't work on Windows, the 5.15.0 version works fine
![image](https://user-images.githubusercontent.com/73971855/189538444-a562c7ac-c09b-4aff-ac19-458a8320eacb.png)

**Comment by daniejstriata** [comment]
I get the same. I forced it to use a log file and then it works.
`gdu_windows_amd64.exe -n -l gdu.log`

**Comment by dundee** [comment]
Ah, my bad.
