### ISSUE TITLE
Sug: use more vert space for filename in scanning box

### ISSUE THREAD

**Issue by edrozenberg** [dundee/gdu#172]
Currently when scanning, if the filename/path is long, `gdu` doesn't display the "Total items" line - that line becomes hidden.

Suggestion: dedicate 2 or 3 lines in the scanning box to the path/filename, and never allow the "Total items" line to be hidden. There is enough vertical space available in the scanning box to fit this, even without making the scanning box taller (and the scanning box could be made taller as well if necessary, plenty of vertical space available in even the smallest terminal windows).

This example shows a long path/filename which causes the "Total items" info to be hidden:

<img width="939" alt="No Total items Shown" src="https://user-images.githubusercontent.com/2648417/189554557-8273bfb8-aad6-45f9-b7e3-c76ca1afa5a6.png">

This is how it normally looks when the "Total items" line is visible:

<img width="924" alt="When It All Fits" src="https://user-images.githubusercontent.com/2648417/189554713-ed06eeef-e418-4f56-acdc-1bca6ccea247.png">

(and don't allow longer/shorter filenames to cause the scanning box layout to change while scanning, that would be distracting, keep the same scanning box layout regardless of the size of the current path)

**Comment by edrozenberg** [comment]
Thanks for the quick fix! It works fine in many cases, still has the same problem when the path+filename is for ex. 4 lines (just saw the problem on one of my servers w/a deep path).

Really liking the multi-core functionality of the tool, much faster in many cases than the similar `ncdu` v2. And appreciate the many pre-built release bins, since many of us don't love the tooling and process involved in building any golang proj.

**Comment by dundee** [comment]
Thanks for report. Unfortunately this is not easy to fix properly. The "total items" line is not overwritten, it's just scrolled out of view since the content of the modal is higher then expected. I can reserve one more line for the modal but that's probably all I can do now.

**Comment by edrozenberg** [comment]
Thank you, 1 more line would help in more cases but there will always be deeper and deeper path structures :). I don't know ncurses so don't know if there's a way to define 2 regions inside the popup, where the region for Total would be always visible.

**Comment by daniejstriata** [comment]
Seeing the Current item has always been cosmetic for me. Why not break down the Current item output to only show the last files or directories (depending on scanning location) if the path is going to contain more characters than the modal can comfortably contain?
![image](https://user-images.githubusercontent.com/13314239/189980725-e3809f13-958a-463d-a58e-3ed8086238ad.png)

**Comment by dundee** [comment]
Yes, that's a good idea. I will prepare something.
