### ISSUE TITLE
Doesn't read external config file (again)

### ISSUE THREAD

**Issue by Ved-un** [dundee/gdu#176]
**gdu v5.18.0**

I enter the path to any file, even those that don't exist - it still reads the default config and shows no errors...

```
[elem] ~ ❯ gdu --config-file /home/elem/.config/gdu/gdu.yaml 
[elem] ~ ❯ gdu --config-file example
[elem] ~ ❯ gdu --config-file example/example
[elem] ~ ❯ gdu --config-file ~/example/example/example/example/abcdf
[elem] ~ ❯ gdu --config-file
Error: flag needs an argument: --config-file
[elem] ~ ❯ 
```

**update**
If I run
`gdu --config-file /home/elem/.config/gdu/gdu.yaml`
then it simply erases my settings in this file and sets its defaults

**Comment by Ved-un** [comment]
I can't clutter up HOME with configs - I have almost everything in the ~/.config folder (XDG_CONFIG_HOME)

everything is clean and tidy

![flameshot_261](https://user-images.githubusercontent.com/48730277/190895436-d52427d4-21d0-472c-a23a-6ca81354c7f3.png)

**Comment by dundee** [comment]
I cannot replicate it. Could you paste your config file?

**Comment by dundee** [comment]
I can replicate. My bad, fix will be released soon.

**Comment by dundee** [comment]
Fixed in https://github.com/dundee/gdu/commit/fa26ea7ef4c2fb655b1f940ae0c1d1d4470345dd.

**Comment by Ved-un** [comment]
Thank you !!!

**Comment by dundee** [comment]
Good! I will probably introduce reading from both `~/.gdu.yaml` and `~/.config/gdu/gdu.yaml` by default. It makes sense.

**Comment by Ved-un** [comment]
> Good! I will probably introduce reading from both `~/.gdu.yaml` and `~/.config/gdu/gdu.yaml` by default. It makes sense.

Now I tried this - no, it does not read my default config

![flameshot_264](https://user-images.githubusercontent.com/48730277/191449721-4e0a1b5e-3403-4fde-ae37-c520f6ff7227.png)

It only works like this `gdu --config-file ~/.config/gdu/gdu.yaml`

**Comment by dundee** [comment]
@Ved-un  Have you tried it on the master branch version? Because the change is not relased yet.

You can install the master version using `go install github.com/dundee/gdu/v5/cmd/gdu@master`
