### ISSUE TITLE
Would you like to support negative sizes?

### ISSUE THREAD

**Issue by lilydjwg** [dundee/gdu#178]
Negative sizes come from a diff of two exported datasets. The only issue gdu has seems to be formatting (it shows -1234567B).

I've written a Python script to do the diff and patched the old written-in-C ncdu to support negative sizes (https://github.com/lilydjwg/ncdu-diff), but I didn't figure out how to patch the newer, nicer witten-in-Zig ncdu. It would be be great for gdu to support it so I can migrate my script to gdu.

**Comment by dundee** [comment]
Hi, it will be added to the next release.
