### ISSUE TITLE
Feature: Show mtime by default, or command-line switch for it

### ISSUE THREAD

**Issue by zoomosis** [dundee/gdu#181]
Can gdu show the mtime by default? I'd prefer not to press 'm' each time at startup.
Or perhaps a --show-mtime command-line switch. Then I can set a shell alias to always run gdu with that option.

**Comment by rwahyudi** [comment]
Please dont make mtime default. 

Main purpose of gdu is to show disk usage and the most important parameter for disk usage usage utilisation is size, so sorting by size should be the default. 

I think a better way is to add the default startup sorting method to config file.

**Comment by dundee** [comment]
Yes, adding a config file parameter for that makes sense.
