### ISSUE TITLE
Export with FullNames

### ISSUE THREAD

**Issue by rNianios** [dundee/gdu#184]
Hi,

When exporting to JSON, there is no option to exprot using the full path.
Rather the export only contains relevant paths. I can't see any option to export using full paths.

Is there?

**Comment by dundee** [comment]
The export format is compatible with the one of `ncdu`. The absolute path is there just once in the "header", e.g.:

```
[1,2,{"progname":"gdu","progver":"development","timestamp":1666468251},
[{"name":"/home/dundee/work/gdu","mtime":1666468247},
```

The absolute paths of all files should be fairly simple to compose programmatically then. 

Does this cover your use case?

**Comment by rNianios** [comment]
Thanks for the answer dundee, I saw the header, I was hoping maybe there was an argument to output the whole path as it would make my use case so much easier than trying to reconstruct the whole path.

I will see what I can do to get the whole path.

**Comment by rNianios** [comment]
@dundee 

Hm... if you have a scan of a whole drive with multiple levels, this becomes troublesome. Any chance a special flag to export the whole path is maybe possible?

**Comment by dundee** [comment]
What do you mean by multiple levels?

**Comment by rNianios** [comment]
I mean that if you scan a whole drive you will get many depths of folders,
so restructuring the whole path is not as easy as if you have a depth of 2
or 3 levels.

**Comment by rNianios** [comment]
@dundee 

Didn't have the time to deal with it at the moment but kept coming back to this. I am not a developer neither I right a lot of python although I am familiar with it. 

Thanks for providing and example. Using your example I was able to create a similar code in powershell, I will provide below, for anyone that might need this in Windows Context. Although using Powershell 7+ this should run on any OS that is supported by version 7 of Powershell.

```

[cmdletbinding()]
param(
    [Parameter(Mandatory = $true, ValueFromPipeline = $true)]
    [string]$jsonFile
)

function  ConvertTo-FullPath {
    param($data,
        [string]$path)

    if (-not ([string]::IsNullOrEmpty($path))) {
        $path = "$($path)\$($data[0].Name)" 
    }
    else {
        $path = "$($path)$($data[0].Name)" 
    }
         
    foreach ($item in ($data | Select -Skip 1) ) {
        if ($item.GetType().BaseType.Name -eq "Array") {
            ConvertTo-FullPath -data $item -path $path
        }
        else {
            $pathLast = "$($path)\$($item.name)"
        }

        [void]$results.Add($pathLast)   
    }    
}

$results = [System.Collections.ArrayList]@()

$data = Get-Content -Raw $jsonFile | ConvertFrom-Json 

$fileInfo = Get-Item $jsonFile
$outputBaseName = $fileInfo.BaseName
$outputDirName  = $fileInfo.DirectoryName   
$outputFileName = "$($outputDirName)\$($outputBaseName).txt"

ConvertTo-FullPath -data $data[3] -path ''

$results | Out-File -FilePath $outputFileName -Encoding UTF8
```
Usage: 

"C:\test\1.json" | C:\test\ConvertTo-FullPath.ps1
The script by default will output a txt file at the same path as the json.
It will have the same name as the json file path with a txt extension. 
That txt file will containthe fullpath of all the files. 

I am usually using gdu to get all the filenames and then scan for known filenames with CVEs, therefore having the wholepath is very helpful. 

PS. There seems to be an issue with gdu oR json formatting, which will cause the filepath that was picked to run gdu against to have an extra trailing backslash. This will also be present at the output. I couldn't care less about an extra backslash being therefore I am leaving it as it is. 

Once again thanks for your work here.

**Comment by dundee** [comment]
Thanks for sharing!
