### ISSUE TITLE
apt outdated

### ISSUE THREAD

**Issue by 030** [dundee/gdu#189]
gdu --version
Version:	 4.6.3-1ubuntu2
Built time:	 2021-03-16_20:52:36
Built user:	 debian

While the current version is 5.X

**Comment by dundee** [comment]
What distribution do you use?

**Comment by daniejstriata** [comment]
Debian buster = gdu_4.6.3-1+b4_amd64
ubuntu 20.04 = N/A
Kali = 5.20.0

**Comment by 030** [comment]
@dundee Ubuntu 20.04.

**Comment by dundee** [comment]
I see. Currently only Ubuntu 22.04 is supported with more recent releases - https://launchpad.net/~daniel-milde/+archive/ubuntu/gdu?field.series_filter=jammy

**Comment by 030** [comment]
ubuntu 22.04:

```
gdu --version
Version:	 5.20.0-1ubuntu1
Built time:	 2022-10-23_20:59:37
Built user:	 debian
```
