### ISSUE TITLE
Unable to send interactive gdu screen to background

### ISSUE THREAD

**Issue by rwahyudi** [dundee/gdu#192]
I no longer able to escape gdu  and send it into background and work on the command line.   Ie CTRL + Z 

I'm pretty sure I was able to do this previously or I might have mistaken it for ncdu. 
If it's the latter - can we allow backgrounding when using intetactive gdu ?

**Comment by dundee** [comment]
That was probably ncdu. Gdu was not having this feature. 

You can spawn shell in the current directory using `b` key. Does it cover your use case?

**Comment by rwahyudi** [comment]
Ah didn't realize gdu has this neat feature! - Yep this would do what I needed
