### ISSUE TITLE
Kali Linux - Compiled older version for repo

### ISSUE THREAD

**Issue by daniejstriata** [dundee/gdu#200]
Latest version installed:
```
# dpkg -l | grep gdu
ii  gdu                                   5.21.0-1                        amd64        Pretty fast disk usage analyzer
```
Printed version is older though.
```
# gdu --version
Version:         v5.20.0
Built time:      Sat Oct 22 10:48:31 PM CEST 2022
Built user:      dundee
```

**Comment by dundee** [comment]
That's weird. Could you be using some local version? 
What's the output of  `which gdu`?

**Comment by daniejstriata** [comment]
> That's weird. Could you be using some local version? What's the output of `which gdu`?

Sorry for waiting your time. I forgot I originally installed it by putting the binary in `/usr/local/bin` and therefore had 2 binaries on the host.
