### ISSUE TITLE
Make key based settings/toggles available through config/command-line

### ISSUE THREAD

**Issue by Impact123** [dundee/gdu#242]
I pretty much always use the `c > Show/hide file count` and `m > Show/hide latest mtime` keys but I couldn't find a way to set these options via the config file or through command-line arguments. Please let me know if it slipped past my eyes.
It would be nice if all the options you can toggle via a keyboard key would also be available via command-line arguments and/or through the config file.
One way that is probably less work would be to define a set of keys that are "pressed" when gdu starts.
```yaml
init-keys: cm
```
```bash
gdu --init-keys=cm
```

**Comment by dundee** [comment]
Sorry, this issue slipped my attention. 

We have added `--show-item-count` (`-C`) option in [5.28](https://github.com/dundee/gdu/releases/tag/v5.28.0).
I will add option for `Show/hide latest mtime` as well.
