### ISSUE TITLE
support for not counting mounts

### ISSUE THREAD

**Issue by anonymouse64** [dundee/gdu#25]
Hi, I tried to use gdu with "/" on my system that has many many many snaps mounted (approximately 316 I think), and each "snap" revision is mounted from a snap file located in /var/lib/snapd/snaps/... onto a directory like `/snap/{name}/{number}`. This resulted in gdu counting the disk usage of /snap/something/2 and /snap/something/3, etc. and ending up taking a long time and totaling to be over twice the actual size of the hard-disk. I wonder if gdu could inspect /proc/self/mountinfo or just the `mountnpoint` command, etc. to determine if a directory is a mount from somewhere else and ignore that for the purposes of calculating disk usage. 

Otherwise I found this to be a really cool application, thanks for building it!

**Comment by dundee** [comment]
Hi, you can use `-i` flag. For example:

```
gdu -i /snap,/var/lib/snapd/snap,/proc,/dev,/sys /
``` 

Gdu does ignore other mounts when running `gdu -d` and selecting one device.

**Comment by dundee** [comment]
Probably another flag like `ncdu -x` could be added for not crossing FS bounderies.

**Comment by nodens** [comment]
Hi, I'm a ncdu user, and while I love gdu I'd like to be able do do something like `gdu -x /` to see what's eating space on / fs without crossing fs boundaries indeed… So +1 from me.
-d is a valid workaround but it's more awkward to use when you're used to `ncdu -x` .
