### ISSUE TITLE
gdu with ssh won't close, 100 percent cpu usage

### ISSUE THREAD

**Issue by Crowley007** [dundee/gdu#266]
GDU v5.25.0
Ubuntu LTS 22.04
Mainline kernel 6.3

This is a weird and somewhat random issue that I have seen lately.  I run gdu on my server which I control with ssh.  Sometimes when logging in and using htop, I see gdu running and consuming 100% of a single core. It's difficult to replicate, I have tried closing the ssh window without closing gdu first, but so far gdu always closes when I try this. I have no idea why it's running sometimes when no ssh connection is active, but I have seen this multiple times.

**Comment by dundee** [comment]
Is it possible that gdu is started by crond?

**Comment by Crowley007** [comment]
There's no reason why it would be. Have not seen this happen lately, it's quite rate.

**Comment by borestad** [comment]
Most likely exactly the same issue as ncdu had (although I've seen it happen anyway still)
https://code.blicky.net/yorhel/ncdu/issues/141

**Comment by noah-de** [comment]
@Crowley007 did you ever figure this out?

I just read your issue and noticed a couple things in your report:

-  "on my server _which I control with ssh_"
- "it's running sometimes _when no ssh connection is active_"

I am not certain how to make sense of those statements. Wouldn't you be seeing the behavior over an active ssh connection? If that is the case, you may want to take a look at the scripts that execute when you login. One is likely .bashrc or .bash_profile in your home directory. Examine the contents of those files to see if there isn't something calling gdu. 
Further investigations could be done by [checking the logs](https://ubuntu.com/tutorials/viewing-and-monitoring-log-files#1-overview).

Based on the link posted by @borestad I am also wondering if both of you are running gdu as root.

I think that gdu is a great tool and would like to keep the discussions and development going.

**Comment by dundee** [comment]
Solution for ncdu was most likely this: https://code.blicky.net/yorhel/ncdu/commit/888bd66
I will check if we can introduce somethink similar.

**Comment by borestad** [comment]
My workaround the last couple of months has been this bash function that sets a timeout (and fixes the broken terminal)

```
gdu () {
	timeout --foreground -s SIGTERM 10m $HOMEBREW_PREFIX/Cellar/gdu/*/bin/gdu-go -x -a -i "$HOME/Library/Mobile Documents" "$@" || (
		stty sane &> /dev/null
		tput reset &> /dev/null
		clear
		echo "[timeout]: 10m gdu"
	)
}
```

**Comment by dundee** [comment]
I hope this was it.
