### ISSUE TITLE
Selected directories are almost invisible

### ISSUE THREAD

**Issue by ouuan** [dundee/gdu#28]
directory: ![1](https://user-images.githubusercontent.com/30581822/107367637-859e5500-6b1a-11eb-919c-3e1e20baeb5c.png)

file: ![2](https://user-images.githubusercontent.com/30581822/107367697-92bb4400-6b1a-11eb-9b50-db0aa65cd2a4.png)

terminal colors (neofetch): ![3](https://user-images.githubusercontent.com/30581822/107367723-9a7ae880-6b1a-11eb-8d37-433dac495000.png)

**Comment by dundee** [comment]
What OS and terminal is it?

**Comment by ouuan** [comment]
> What OS and terminal is it?

konsole on Arch Linux. But I think only the terminal colors matter, so I only provided the colors.

![colors](https://user-images.githubusercontent.com/30581822/107445694-ed36bd80-6b77-11eb-9e90-ec9a7e111375.png)

**Comment by dundee** [comment]
Looks like konsole does not support Xterm/ECMA-48 colors. I will set explicit RGB values.
