### ISSUE TITLE
Default colors are unreadable

### ISSUE THREAD

**Issue by huyz** [dundee/gdu#280]
Sure we can disable colors with `-c` and .gdu.yaml, but why have default colors that are hard to read.

On my screen the default colors at the bottom look like this:

![screenshot 2023-10-02T093016Z](https://github.com/dundee/gdu/assets/128394/a996e280-d691-47c5-b52a-c2defd333629)

Even in the README, you have:

![screenshot 2023-10-02T092818Z](https://github.com/dundee/gdu/assets/128394/b97b4fc8-1382-46ff-96fb-99610f29e2f4)

I don't know about your display, but for me the red on blue is not readable.

Changing colors for taste is one thing.  But having default colors that are readable really should be standard.

**Comment by dundee** [comment]
I will check the colors. It should be black and white, the grey is there by mistake.

**Comment by dundee** [comment]
I think I have found the cause. You probably have first color in your color palette mapped to something different then black. I have selected the color more explicitly now.

For future testing: which terminal, OS and colors theme do you use?

**Comment by huyz** [comment]
You're right. My bad.
I'm using iTerm on macOS, with the "Violet Light" theme from https://iterm2colorschemes.com/
The palette looks like:
![screenshot 2024-02-18T205507Z](https://github.com/dundee/gdu/assets/128394/3f35a7c0-7087-4de3-a2bc-b5f15744f47e)

**Comment by dundee** [comment]
Thanks, I will check that theme.
