### ISSUE TITLE
macos no detecting tty

### ISSUE THREAD

**Issue by jorpilo** [dundee/gdu#282]
when running gdu (installed through brew) it always uses non-iterative mode and I can't make it run interactive.

I have tried in terminal and iterm2 and with zsh, bash and fish shells and it always runs non-interactive.

Any help on why it is not detecting the terminal.

**Comment by jorpilo** [comment]
```
> echo $TERM
xterm-256color

> tty
/dev/ttys000

> gdu
404	./dir0
808	.

> gdu dir0/*
400	dir0/hs_err_pid26455.log
0	dir0/javaVersionList.txt
4	dir0/list.manifest.json

```

**Comment by daniejstriata** [comment]
If you execute `\gdu` is it still the same?

**Comment by Kondratenko-Valeriy** [comment]
Same issue.
Using `\gdu` also runs in non-interactive mode.

**Comment by dundee** [comment]
You are running GNU `du` from coreutils, which links to path `bin/gdu` in brew.

```
brew install gdu
# gdu will be installed as `gdu-go` to avoid conflicts with coreutils
gdu-go
```
