### ISSUE TITLE
Add keybinding for ignoring directory under the cursor

### ISSUE THREAD

**Issue by knuesel** [dundee/gdu#292]
I often have directories that look like this:

```
   30.3 GiB [#######   ] /a                                                                                                           
    2.2 GiB [          ] /b                                                                                                          
    2.5 MiB [          ] /c                                                                                                      
   92.3 KiB [          ] /d
   ...
```

In such cases the graphical bars are not very useful...

I'd love being able to move to the first entry and press `I` (or something) to add it to the list of ignored directories.

**Comment by dundee** [comment]
That's a nice idea!

**Comment by dlidstrom** [comment]
Please also consider this to handle individual files too. Ideally (IMHO) the filename would be written to the absolute paths pattern file that was specified with `-X`. Thanks!

**Comment by knuesel** [comment]
Thank you!!
