### ISSUE TITLE
Feature request: background deletion

### ISSUE THREAD

**Issue by axet** [dundee/gdu#293]
Hello!

Cleaning big HDD can be very slow. Deleting one folder can take 10 minutes. During this time I prefer keep navigating and adding to deleting queue.

Deleting can be done in background or at once at exit using selection which should support multifolder / tree selection (not just current folder).

Also having deletion progress (current item, time, count, size) could be usefull.

EDIT: Background deleting may looks like this: 1) Deleting dialog can be minimized using 'B' key 2) after pressing 'B' deleting keep going in background with status bar minimum updates (current file) and rotating arrow. Background deleting should update main window and reduce know folders sizes 3) navigating keep working and allowing to delete more folders, adding them to deleting queue 4) pressing 'B' restoring deleting window

**Comment by dundee** [comment]
This looks like very good idea! Thanks!
