### ISSUE TITLE
Always Scanning

### ISSUE THREAD

**Issue by Jackiexiao** [dundee/gdu#296]
gdu stuck and always scanning.... no response

**Comment by dundee** [comment]
Could you add more details? Is it reproducible? Which version od Gdu and what OS are you using?

**Comment by Jackiexiao** [comment]
thx for your reply
```
./gdu -v
Version:	 v5.25.0
Built time:	 Tue Jun  6 02:51:34 PM CEST 2023
Built user:	 dundee
```
Ubuntu 18.04.6 LTS

It is reproducible, but only on my server, I scan a  > 100T disk. 
It’s reassuring to see that gdu is still actively scanning, as evidenced by the display of the increasing count of files, which confirms it is tirelessly processing through a directory with numerous small files.

**Comment by dundee** [comment]
Thanks for details. 

Ok, that's a lot of data. Isn't Gdu running out of memory in the first place?

**Comment by Jackiexiao** [comment]
no, I have >300G memory, but gdu did consume a lot of memory (>60G). looks like it's my disk's problem...... I've rescreened it now, and there's no problem

**Comment by dundee** [comment]
Great! 

Feel free to also try the new `--use-storage` and `--read-from-storage` options that come with Gdu 5.26.
It will run much slower, but use less RAM and also you can then reopen the results later.
It's still experimental though so you might hit some problems.

**Comment by Jackiexiao** [comment]
thx
