### ISSUE TITLE
[Feature Request] Add multiple column feature like godu

### ISSUE THREAD

**Issue by c02y** [dundee/gdu#30]
gif demo from godu project home page:
![54609718-cf2bb580-4a53-11e9-8cd0-2272278597b6](https://user-images.githubusercontent.com/2135996/107938674-afdf8f00-6fc0-11eb-8144-8fef2cc86d82.gif)

**Comment by dundee** [comment]
Godu has quite different philosophy of user-interface. I don't think this two can be combined successfully.
