### ISSUE TITLE
How to make the background transparent like terminal itself?

### ISSUE THREAD

**Issue by c02y** [dundee/gdu#31]
When my terminal has a transparent background(opacity), how to make gdu use the transparent of the terminal like ncdu/dua?

**Comment by dundee** [comment]
Good point, I will try to fix it.

**Comment by c02y** [comment]
I tested it using `go get -u github.com/dundee/gdu`, and there are multiple issues of this version:
1. the transparent feature doesn't work in alacritty, but works in kitty
2. no color
3. gdu without argument and option is not scanning the current directory,  but the same result of `gdu -d` of old version(v4.4.1 installed from Manajro repo)
4. the help page of the new version is very short, only 3 options(-ignore, -log-file, -v), but old version(v4.4.1) has 9 options

**Comment by dundee** [comment]
You probably installed some old version, not the current master (maybe some cache?). 
You can try to clone this repo and run `go run .` or wait for the release.

**Comment by c02y** [comment]
It works again by using `go get -u github.com/dundee/gdu` or `go run .`, weird.

**Comment by dundee** [comment]
Great. I have shipped 4.6.2 in the meantime.

**Comment by c02y** [comment]
Another thing: should the popup help window follow the same rule too?

**Comment by dundee** [comment]
Probably should, but the rivo/tview renders then all the layers/pages, so it's quite unreadable. I am not sure if it can be disabled somehow. 
See ![screenshot](https://user-images.githubusercontent.com/27106/108172708-6ba5d900-70fd-11eb-9fb9-e407878b2ccd.png).

Gdu doesn't have `g` key binding yet. I don't see it so important.

**Comment by c02y** [comment]
> Probably should, but the rivo/tview renders then all the layers/pages, so it's quite unreadable. 

yeah, that is one problem, I guess I'm OK with the current solution.

> Gdu doesn't have g key binding yet. I don't see it so important.

Really? Every time I hit `G`, the point goes to the bottom of the list, and `g` goes to the top of the list, maybe it is from other module?

**Comment by dundee** [comment]
> Really? Every time I hit `G`, the point goes to the bottom of the list, and `g` goes to the top of the list, maybe it is from other module?

You are right, these are key bindings of the tview library. I should add them to the help too.
