### ISSUE TITLE
ENTER key not working when navigating loaded json file

### ISSUE THREAD

**Issue by adioni** [dundee/gdu#311]
Hello,

When running gdu 'live' against, say, my home directory, e.g.:

`$ gdu $HOME`

...navigating in and out of subdirectories using the arrow keys and ENTER key works as expected.

However if I run gdu, save the analysis to an output file, and then later run gdu against that file, e.g.:

```
$ gdu $HOME -o home-dir-scan.json
$ gdu -f home-dir-scan.json
```

...trying to navigate into subdirectories using the ENTER key or up a level by highlighting **../** up top and hitting the ENTER key both do nothing.

**Comment by dundee** [comment]
Thanks for the eport. I'm able to reproduce and will investigate what's wrong.
