### ISSUE TITLE
Sway Keybinding Conflicts

### ISSUE THREAD

**Issue by Montana** [dundee/gdu#374]
**Describe the bug:**

I found out the hard way that Sway's keybindings are conflicting with `gdu` or `feh`. So I highly recommend you review your Sway configuration files (usually located in `~/.config/sway/config` or similar) and ensure there are no conflicting keybindings that might prevent `gdu` from passing the `o` key press to `feh`.

**System (please complete the following information):**

 - OS: macOS (MacBook Pro M3 Max 14.2" / 96GB Ram / 40 Cores)
 - Terminal iTerm2
 - Build 3.5.0 (of iTerm2)

**Additional context:**

Just wanted to make people aware of this - this is what was causing my issues. I was able to run:

```bash
bindsym $mod+o exec gdu
```
Then did a verbose output:

```bash
gdu --verbose
```
I reviewed logs via `journalctl -xe` for `systemd `logs, and specific logs for `gdu`, it was quite obvious this is what was happening. 

I then ran:

```bash
xdg-mime default feh.desktop image/jpeg
``` 
Everything worked fine, this is more of a cautionary tale, and I could see how this could easily happen to someone. Thanks for all your hard and great work @dundee!

**Comment by dundee** [comment]
Thank you for your report!
