### ISSUE TITLE
[request] - Add SHA256 hashes to releases

### ISSUE THREAD

**Issue by kquinsland** [dundee/gdu#38]
Hi!

Is there any chance that you can update your CCI automation to also build a simple text file w/ the sha256 hashes of each release artifact? Ideally, in the same format as the [Prometheus node exporter](https://github.com/prometheus/node_exporter)  

[E.g.:](https://github.com/prometheus/node_exporter/releases/download/v1.1.2/sha256sums.txt)

```
3919266f1dbad5f7e5ce7b4207057fc253a8322f570607cc0f3e73f4a53338e3  node_exporter-1.1.2.darwin-amd64.tar.gz
5b0195e203dedd3a8973cd1894a55097554a4af6d8f4f0614c2c67d6670ea8ae  node_exporter-1.1.2.linux-386.tar.gz
<...>
```

Having the hash for each artifact makes it much easier to automatically fetch / verify binaries in various automation / system build processes.

**Comment by dundee** [comment]
Added to 4.8.1 release with additional gpg signature. Is the format ok?

**Comment by kquinsland** [comment]
PGP is even better :) Can you link to the public key?

I can't find the key anywhere:
https://keyserver.ubuntu.com/pks/lookup?search=360B658707A1A44CA57FB67EEF0BA1C4F3990103&fingerprint=on&op=index

But i can find your fingerprint elsewhere:

https://nm.debian.org/person/dundee/

**Comment by dundee** [comment]
I have submited my key to keyservers several times but it doesn't work for some unknown reason.

I have even tried manual submiting via the web form, it said ok and still no key there :) Maybe I am missing something.

http://hkps.pool.sks-keyservers.net/pks/lookup?search=EF0BA1C4F3990103&fingerprint=on&op=index

**Comment by kquinsland** [comment]
> I have submited my key to keyservers several times but it doesn't work for some unknown reason.

Any chance you can upload the key here? I can import it into my build pipe so releases can be verified.

**Comment by dundee** [comment]
I have the key uploaded on Github, it it's what you are asking about.
Fingerprint: `EF0BA1C4F3990103`.
