### ISSUE TITLE
Adding a new installation method to the README

### ISSUE THREAD

**Issue by lunrenyi** [dundee/gdu#381]
- Hi, we have implemented a lightweight [package manager using shell and awk](https://www.x-cmd.com/pkg/).
It helps you download gdu release packages from the internet and extract them into a unified directory for management, without requiring root permissions.

- **I mean, can the installation method provided by x-cmd be added to the gdu README?**[The installation method for the x command](https://www.x-cmd.com/start/)
  ```sh
  x env use gdu
  ```

Looking forward to your reply :) !

**Comment by dundee** [comment]
Added in https://github.com/dundee/gdu/commit/836c39a626a3e95cfbc14219c4cf920a491ec8ca, thanks for reaching out!
