### ISSUE TITLE
Ubuntu 24.04 "noble" release file?

### ISSUE THREAD

**Issue by lnlyssg** [dundee/gdu#384]
Is there any chance of Ubuntu 24.04 being added to the releases please? It's not at http://ppa.launchpadcontent.net/daniel-milde/gdu/ubuntu/dists/ so causes an error when trying to install under 24.04:

Failed to update apt cache:
E:The repository 'https://ppa.launchpadcontent.net/daniel-milde/gdu/ubuntu noble Release' does not have a Release file.

**Comment by dundee** [comment]
Yes, I will add support for it.

**Comment by dundee** [comment]
Added. Please try it and report back if anything goes wrong.
