### ISSUE TITLE
deleting wrong files

### ISSUE THREAD

**Issue by leapfog** [dundee/gdu#388]
**Describe the bug**
gdu deletes the wrong files

**To Reproduce**
1. mark some files for deletion (with Space key)
2. change sort order (by size/by name/...)
3. type d to delete the wrong set of files

Same happens when "/" is used to filter files.

**Expected behavior**
Remember marked files by *filename*, not by *position*.
(Or clear the list of marked files, when changing order.)

**System:**
 - OS: Gentoo Linux
 - Terminal: XTerm
 - Version: v5.29.0

**Comment by dundee** [comment]
Oh, that is nasty bug. Thanks for report!
