### ISSUE TITLE
Permit to show full path during scan

### ISSUE THREAD

**Issue by henri9813** [dundee/gdu#389]
**Is your feature request related to a problem? Please describe.**
Hello,

First, thanks to develop `gdu`.

During the scan, I would like to be able to see the full path instead of shortened one.

<img width="1334" alt="image" src="https://github.com/user-attachments/assets/389e0ed9-31c7-4420-b1b6-680d605545e3">

**Describe the solution you'd like**

`gdu --no-wrap-path` ( or whatever you want ).

**Describe alternatives you've considered**

**Additional context**

**Comment by dundee** [comment]
This was already implemented in dundee/gdu#174

The only think you need to do is to set `current-item-path-max-len` in the config file. E.g. like so:

```yaml
style:
    progress-modal:
        current-item-path-max-len: 1000
```

**Comment by dundee** [comment]
I will write some documentation for it.

**Comment by henri9813** [comment]
Thanks !
