### ISSUE TITLE
enter doesn't do the same as l/right

### ISSUE THREAD

**Issue by M1cha** [dundee/gdu#39]
I have certain directories where enter works as expected, but l and right enter the directory without showing any files(not even `/..`)
I'm not yet sure what's so special or different about these directories so I can't really tell you how to reproduce it.
So if you have any ideas or want me to test something, just tell me :)

**Comment by dundee** [comment]
Do these directories have some special name or something?

**Comment by jpralves** [comment]
I've watched the same behaviour but it only manifests sometimes.... maybe an initialization problem ?
The folder with that behaviour has a subfolder with ( ) in its name.

**Comment by M1cha** [comment]
I did some tests and apparently long filenames(>115) are a problem.

**Comment by dundee** [comment]
@M1cha Could you upload some example dir? I have tried some very long names (even with spaces, diactitics, braces in it) and haven't noticed any issue.

**Comment by jpralves** [comment]
Try with the following folder:
`
mkdir -p 123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
`

**Comment by dundee** [comment]
@jpralves Nice! Thank you. I can replicate it now.
