### ISSUE TITLE
add a nested json for a folders

### ISSUE THREAD

**Issue by Nagurbi** [dundee/gdu#390]
The current json output is as below, if there is a way to distinguish between a file and a folder it would be easy to extract full path. 

[
    1,
    2,
    {
        "progname": "gdu",
        "progver": "v5.29.0",
        "timestamp": 1732707880
    },
    [
        {
            "name": "/root/user",
            "mtime": 1732673732
        },
        [
            {
                "name": "folder",
                "mtime": 1699686175
            },
            {
                "name": "file",
                "asize": 1039,
                "dsize": 4096,
                "mtime": 1699384344
            }
]]]

**Comment by dundee** [comment]
It's quite easy. If the item in the array is an array itself, then it's a folder. 

```python
out = [1,2,{"progname":"gdu","progver":"v5.28.0","timestamp":1732790270},
    [
        {"name":"/home/dundee/w/gdu/test","mtime":1732790268},
        [   # an array -> this is a directory
            {"name":"x","mtime":1732790268}, # directory name
            {"name":"z","mtime":1732790268}
        ],
        {"name":"d","mtime":1718612605}, # normal files
        {"name":"c","mtime":1718612605},
        {"name":"b","mtime":1718612605},
        {"name":"a","mtime":1718612605}
    ]
]

def print_path(item, path=""):
    if isinstance(item, list):
        for i in item[1:]:
            print_path(i, path + item[0]['name'] + '/')
    else:
        print(path + item['name'])

print_path(out[3])

# Output:
# /home/dundee/w/gdu/test/x/z
# /home/dundee/w/gdu/test/d
# /home/dundee/w/gdu/test/c
# /home/dundee/w/gdu/test/b
# /home/dundee/w/gdu/test/a
```
