### ISSUE TITLE
Hardlink Bug?

### ISSUE THREAD

**Issue by PedroBuffon** [dundee/gdu#394]
**Describe the bug**
When files are hardlinked by Sonarr or any other software, they are only recognized as hardlinks if both paths involved in the hardlinking process are present simultaneously in the file system. This can cause confusion or lead to incorrect detection of hardlinked files.

**To Reproduce**
1. Set up the following folder structure:
/data
├── torrents
│   ├── animes
│   ├── movies
│   └── series
└── media
    ├── animes
    ├── movies
    ├── series

Files on torrents/series are hardlinked to media/series, if you run gdu command inside the torrents folder, no hardlink tags are shown, they only appear if you run gdu on the root of both folder, on the /data

**Expected behavior**
Files in /data/media/series should remain tagged as hardlinks, even if the gdu command is ran outside the folder.

**System (please complete the following information):**
 - OS: Debian 12
 - Terminal: Termius/powershell
 - Version: 5.22.0-1+b1

**Comment by dundee** [comment]
You are right. Thanks for the report!
