### ISSUE TITLE
Runtime error while scanning home partition

### ISSUE THREAD

**Issue by shubhamgupta2956** [dundee/gdu#40]
![2021-03-18_08-46-37-](https://user-images.githubusercontent.com/43504292/111568367-9fd8ec00-87c6-11eb-8788-27d9f1aca169.png)
I got the above runtime error while running a scan in the home directory. Please let me know if some other information is needed for solving this issue

**Comment by dundee** [comment]
Looks like there was some file removed/renamed while being scanned, which is not handled correctly.

**Comment by shubhamgupta2956** [comment]
Thanks :)
