### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by samhh** [dundee/gdu#42]
Nothing comes up for `man gdu`. I'm guessing this is because one hasn't been written, though it's also possibly a packaging error on my distro.

**Comment by dundee** [comment]
What distro and installation process are you using?

**Comment by samhh** [comment]
Arch, AUR package [gdu-bin](https://aur.archlinux.org/packages/gdu-bin/).

**Comment by dundee** [comment]
`gdu-bin` doesn't contain man page because it downloads only the released binary. 

Please use [gdu](https://aur.archlinux.org/packages/gdu/) package instead.

**Comment by samhh** [comment]
It's possible to use multiple sources. I may be making a faulty assumption but I think most people using `-*bin` packages do so to minimise dependencies and build resources, not to save bandwidth.

As an aside, tying into this, I believe gdu-bin should be sourcing the project license per the [wiki](https://wiki.archlinux.org/index.php/PKGBUILD#license):


> The BSD, ISC, MIT, zlib/png, Python and OFL licenses are special cases and could not be included in the licenses package. For the sake of the license array, it is treated as a common license (license=('BSD'), license=('ISC'), license=('MIT'), license=('ZLIB'), license=('Python'), and license=('OFL')), but technically each one is a custom license, because each one has its own copyright line. Any package licensed under these five should have its own unique license file stored in /usr/share/licenses/pkgname/.

**Comment by dundee** [comment]
Sounds reasonable. I have added the man page to `gdu-bin` and the license as well.

Thanks for your suggestions!
