### ISSUE TITLE
light gray text on light background

### ISSUE THREAD

**Issue by pkpowell** [dundee/gdu#43]
Is there a way to darken the light gray styled text to make it more legible on terminals with a light background?

**Comment by dundee** [comment]
Not yet. Which terminal and with what background color are you using? Could you paste a screenshot of your terminal running gdu?

**Comment by pkpowell** [comment]
It's the Mac terminal with the Basic (Default) profile which has a white background. It works great, just a bit hard to read.

<img width="1072" alt="Screenshot 2021-03-22 at 07 37 08" src="https://user-images.githubusercontent.com/6270966/111949726-8515b880-8ae1-11eb-82a9-02ce8671d65a.png">

**Comment by dundee** [comment]
There is problem in rivo/tview with transparent modals but I will do my best to improve the colors :)
