### ISSUE TITLE
zfs filesystems are missed due to check for /dev

### ISSUE THREAD

**Issue by HahUK** [dundee/gdu#5]
The following code prevents the detection of zfs mounts as potential "devices" to be scanned.

```
        file, err := os.Open("/proc/mounts")
        if err != nil {
                log.Fatal(err)
        }
        defer file.Close()

        scanner := bufio.NewScanner(file)
        for scanner.Scan() {
                line := scanner.Text()
                if line[0:4] == "/dev" {
```

Thanks,

Tom

**Comment by dundee** [comment]
Could you paste here how the zfs line in `/proc/mounts` looks like? Thanks

**Comment by HahUK** [comment]
Hi,

Sorry for the delay, some example zfs lines from /proc/mounts below:

rootpool/opt /opt zfs rw,nodev,relatime,xattr,posixacl 0 0
rootpool/usr/local /usr/local zfs rw,nodev,relatime,xattr,posixacl 0 0
rootpool/home/root /root zfs rw,nodev,relatime,xattr,posixacl 0 0
rootpool/usr/games /usr/games zfs rw,nodev,relatime,xattr,posixacl 0 0
rootpool/home /home zfs rw,nodev,relatime,xattr,posixacl 0 0

Thanks a lot,

Tom

**Comment by dundee** [comment]
Thank you! Support added.
