### ISSUE TITLE
Option to ignore hidden dirs

### ISSUE THREAD

**Issue by alaymari** [dundee/gdu#50]
Just as the title suggests, can an option be provided to ignore hidden dirs? I tried

    $ gdu -i /home/name/.[a-zA-Z]*
    Error: accepts at most 1 arg(s), received 138

It did not work.

**Comment by dundee** [comment]
Nice idea! I will add it to the next release.

**Comment by alaymari** [comment]
Thanks. Look forward to it.

**Comment by alaymari** [comment]
Thanks for including a new option `-H`. I just noticed a typo there. It is `beginning` rather than `beggining`.

**Comment by dundee** [comment]
> Thanks for including a new option `-H`. I just noticed a typo there. It is `beginning` rather than `beggining`. Look forward to the release with this option/

Just released. Thanks for notice, I will fix it in the next patch version.
