### ISSUE TITLE
Feature: Empty instead of delete a useful directory.

### ISSUE THREAD

**Issue by zhangsean** [dundee/gdu#62]
Feature: Empty instead of delete a useful directory.

Some useful directories have a lot of large files, e.g. `logs`. 
I usually empty the logs directory but don't delete it, becuse the application uses the logs directory all the time, delete the logs directory may cause application errors.

If this feature is acceptable, I will push a PR for this.

**Comment by dundee** [comment]
Hello, zhangsean,
how would you like to implement it? Adding another button to the deletion dialog?

**Comment by zhangsean** [comment]
Add a shortcut key `e` mapping for empty directory, just like shortcut key `d` maping for deleting directory.
&nbsp;

信心+开心=顺心


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Daniel ***@***.***&gt;; 
发送时间: 2021年7月1日(星期四) 下午3:34
收件人: ***@***.***&gt;; 
抄送: "Sean ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dundee/gdu] Feature: Empty instead of delete a useful directory. (#62)





 
Hello, zhangsean,
 how would you like to implement it? Adding another button to the deletion dialog?

**Comment by dundee** [comment]
Great, I think it will be a nice addition.
