### ISSUE TITLE
Save and restore to file

### ISSUE THREAD

**Issue by jtagcat** [dundee/gdu#64]
From ncdu manpages:
```
       Since scanning a large directory may take a while, you can scan a directory and export the results for
       later viewing:

         ncdu -1xo- / | gzip >export.gz
         # ...some time later:
         zcat export.gz | ncdu -f-
```

**Comment by rwahyudi** [comment]
I did ask for the same functionality  😄 
https://github.com/dundee/gdu/discussions/59

**Comment by dundee** [comment]
Closing as duplicate to #59. Thanks!

**Comment by jtagcat** [comment]
> I did ask for the same functionality smile
> #59

Pardon, many projects have discussions enabled, yet they are not used and discouraged. I searched for duplicates in issues, as such, didn't see that.

**Comment by dundee** [comment]
Released in 5.3.0 - https://github.com/dundee/gdu/releases/tag/v5.3.0

**Comment by rwahyudi** [comment]
Tested and work well! 

Very minor compatibility issues is that file generated by ncdu can't be read.
ncdu can read file generated by gdu.

Also minor change in README  needed : 
From : 
gdu -o- / | gzip >report.json.gz
to 
gdu -o- / | gzip -c >report.json.gz

**Comment by dundee** [comment]
Thanks for feedback! Readme and compatibility issues fixed in https://github.com/dundee/gdu/commit/045ad4d1067747d7463432c168c20c8550961ea4
