### ISSUE TITLE
Feature: Quickly view the head or tail of the selected file

### ISSUE THREAD

**Issue by zhangsean** [dundee/gdu#65]
Quickly view the head or tail of the selected file, it's helpful to confirm if the file is deletable.

Suggestion:
The key `h` mapping for quickly view the head of the selected file.
The key `t` mapping for quickly view the tail of the selected file.

**Comment by dundee** [comment]
There is already possibility to show contents of a file with the `v` key binding. When opened, you can scroll to the end of file using `G` or `ctrl+end`. Is it usable for you?

**Comment by zhangsean** [comment]
Sorry for don't notice the `v` key binding to view file content.
