### ISSUE TITLE
Sharing another benchmark for nnn

### ISSUE THREAD

**Issue by jarun** [dundee/gdu#7]
I was referring to the [benchmark](https://github.com/dundee/gdu#benchmark) section and decided to run it on my personal system. I have a SSD drive (stats are du:91.562G free:19.316G files:358098).

I got the the following results at cold boot with gdu and nnn:

```
$ time gdu-linux-amd64 /
gdu-linux-amd64 /  2.24s user 2.48s system 149% cpu 3.153 total  
$ time nnn -T d /
nnn -T d /  0.17s user 4.06s system 36% cpu 11.504 total
```

Considering the CPU usage difference also I see the user+system time is comparable: gdu 4.72s, nnn 4.23s.

ATM I am not sure why the benchmarks vary so much so wanted to share this.

**Comment by dundee** [comment]
You mean why nnn and gdu vary or why your and mine benchamarks vary?

My results:

```
$ sync; echo 1 > /proc/sys/vm/drop_caches
$ time gdu /

real	0m6,646s
user	0m7,938s
sys	0m7,470s
$ sync; echo 1 > /proc/sys/vm/drop_caches
$ time nnn -T d /

real	0m31,119s
user	0m0,363s
sys	0m7,115s
```

**Comment by jarun** [comment]
I took the readings at cold boot so nothing was cached.

Anyway, user+sys would account for the [actual CPU time usage](https://stackoverflow.com/a/556411/3161329) which in your case is: gdu 15408s, nnn 7478s.

**Comment by jarun** [comment]
I think it would be a good idea to publish the actual CPU time usage (user+sys) along with the real (wall clock) time usage given most of the utilities you are running the benchmark against are single-CPU.

**Comment by dundee** [comment]
Good idea, I will add it.

**Comment by jarun** [comment]
Thanks for checking it out!
