### ISSUE TITLE
combined options (sometimes) don't work

### ISSUE THREAD

**Issue by leapfog** [dundee/gdu#76]
The following command uses colorized output:

> $ gdu -c -o gdu.out

The following command (after selecting "/") scans/shows an nfs-mounted directory below /mnt/.hostname

> $ gdu -d -x

(while a loop-mounted ISO image at /mnt/cdrom is ignored as expected)

**Comment by dundee** [comment]
@leapfog Could you create another issue for the mount problem and add some more info? 

How is the nfs mounted? Is it on Linux? Using fuse or mount? Do you see it in `/proc/mounts`? If so, could you copy the line there?
