### ISSUE TITLE
file size vs. disk usage

### ISSUE THREAD

**Issue by dominikholler** [dundee/gdu#8]
Is gdu to get the sum of the file sizes or about the sum of the disk usage?

**Comment by dundee** [comment]
Gdu now only counts apparent size of files. 

Maybe later support for exact disk usage will be added but it's not on roadmap now.

**Comment by ouuan** [comment]
> Maybe later support for exact disk usage will be added but it's not on roadmap now.

I'd suggest keeping this issue open with a label like "low priority" or something like that. I was about to request this just now.

Let me add a reason for this: we usually use xxdu when we want to free the disk. In this case, the disk usage is more useful.

**Comment by dundee** [comment]
Ok, good point. Thanks!
