### ISSUE TITLE
Question - throttle when under load

### ISSUE THREAD

**Issue by daniejstriata** [dundee/gdu#81]
Hi,

Does gdu take in consideration if a system is under load? If under existing high IOps can gdu run single thread not to add more load even if it then runs slower to complete? If not, would that be something to consider?

Danie

**Comment by dundee** [comment]
Hi,
I don't think it's desirable. Sometimes you could want it to finish asap despite the high load (to be able to fix fast no space left etc.), sometimes you could want to lower the load (to be able to interact with the system etc.). It would also be hard to guess the threshold when to lower the process usage.

You can always use the `--max-cores` option to lower the number of cores used.
