### ISSUE TITLE
Normalize the size bar

### ISSUE THREAD

**Issue by OliverLew** [dundee/gdu#82]
I guess the size bar currently shows  the percentage of the file relative to the whole folder. It would be better to set the largest one to 100%, and the others change proportionally, as ncdu does.

**Comment by dundee** [comment]
Why do you think it would be better? I think the current way is more logical. You would loose the graphical reference between the size of the whole folder and its files. You wouldn't see at the first sight if the greatest file consumed all the space or not.

**Comment by OliverLew** [comment]
My thought is to maximize the usage of the bar's space. There is already total size in the status bar, so it is easy to know if the largest file is taking up the most space. Also, if so, you will see one size bar much longer than any other ones anyway.

In my case, my home folder has a few folders with similar size, now I am seeing all the size bars only have two `#`s or less, while the space could show 10:
```
   35.6 GiB [##        ] /VM
   34.8 GiB [##        ] /Music
   27.9 GiB [#         ] /Documents
   22.0 GiB [#         ] /Videos
   20.0 GiB [#         ] /Downloads
   10.1 GiB [          ] /Pictures
... ...
```

What `ncdu` shows:
```
   35.6 GiB [###########] /VM
   34.8 GiB [########## ] /Music
   27.9 GiB [########   ] /Documents
   22.0 GiB [######     ] /Videos
   20.0 GiB [######     ] /Downloads
   10.1 GiB [###        ] /Pictures
... ...
```

It's a matter of whether the size bar should prioritize showing the absolute or relative size, then.

**Comment by dundee** [comment]
I am not sure for now if the usage of the bar's space is so important. I see it as two approches: ncdu shows comparison of sizes of the items. Gdu (and dua) shows disk usage of the items in the context of the current directory. 

The example of `/usr/share/icons/Adwaita/256x256/legacy/` is interesting thanks for it.

My idea: you can have two scenarios which would look the same in ncdu but are different in fact:

You will have one big file and many many small files in one directory. 

1. the big file will occupy most of the space used by the whole directory
2. the big file is much larger then the small files, but they are so many that in the end the big file will occupy only some part of the whole usage

Both cases will seem the same in ncdu, but will be shown differently in gdu. It seems to be that the gdu/dua approach is more correct in the context of disk usage.

**Comment by OliverLew** [comment]
Yes, now we see, the two ways both have their own flaws, and serve different purposes. So I agree to disagree.

**Comment by dundee** [comment]
Ok, thanks. Closing for now.
