### ISSUE TITLE
snap - failure to run from extra drives

### ISSUE THREAD

**Issue by daniejstriata** [dundee/gdu#84]
Hi,

In v 5.5.0 I can not run the gdu snappy from a drive which is not the primary drive. I got the same error from 5.4.0 too.

I believe it is only necessary to use the hostfs path when you are not on the primary drive.

run gdu from /Data:
![image](https://user-images.githubusercontent.com/13314239/127819563-54f05c0b-1e64-42dd-ac10-78105ec56fa2.png)

Config:
fstab:
```
/dev/mapper/vgmint-root /               ext4    errors=remount-ro 0       1
/dev/mapper/sda		/Data		ext4	defaults	0	0
```
```
→ snap  connections | grep gdu
mount-observe             gdu-disk-usage-analyzer:mount-observe  :mount-observe                   -
system-backup             gdu-disk-usage-analyzer:system-backup  :system-backup                   -
```
```
→ snap info gdu-disk-usage-analyzer 
name:      gdu-disk-usage-analyzer
summary:   Disk usage analyzer with console interface written in Go.
publisher: Daniel Milde
store-url: https://snapcraft.io/gdu-disk-usage-analyzer
contact:   daniel@milde.cz
license:   unset
description: |
  Pretty fast disk usage analyzer written in Go. Inspired by ncdu, godu and df.
commands:
  - gdu-disk-usage-analyzer.gdu
snap-id:      v6mWlpSzqaEXy6Vhxhn9wQcMJ9LhrOZy
tracking:     latest/stable
refresh-date: yesterday at 20:16 SAST
channels:
  latest/stable:    v5.5.0 2021-08-01 (757) 1MB -
  latest/candidate: ↑                           
  latest/beta:      ↑                           
  latest/edge:      v5.5.0 2021-08-01 (757) 1MB -
installed:          v5.5.0            (757) 1MB -
```

**Comment by dundee** [comment]
What command do exactly run? `gdu /Data`?

Could you also paste the result of `gdu -dn` ?

**Comment by daniejstriata** [comment]
Hi,

I cd'ed into /Data and ran gdu to get the error.

When I run "gdu /Data​" from home I don't get an error message.

→ gdu -dn
                 Device      Size      Used      Free Used% Mount point
             /dev/loop6  61.9 MiB  61.9 MiB       0 B  100% /
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /etc
             /dev/loop6  61.9 MiB  61.9 MiB       0 B  100% /etc/nsswitch.conf
             /dev/loop6  61.9 MiB  61.9 MiB       0 B  100% /etc/apparmor
             /dev/loop6  61.9 MiB  61.9 MiB       0 B  100% /etc/apparmor.d
             /dev/loop6  61.9 MiB  61.9 MiB       0 B  100% /etc/ssl
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /home
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /root
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /tmp
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /tmp
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /var/snap
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /var/lib/snapd
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /var/lib/snapd/hostfs
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /var/lib/snapd/hostfs
        /dev/mapper/sda 820.5 GiB 722.6 GiB  98.0 GiB   88% /var/lib/snapd/hostfs/run/timeshift/backup
         /dev/nvme0n1p2 704.5 MiB 366.1 MiB 338.4 MiB   52% /var/lib/snapd/hostfs/boot
         /dev/nvme0n1p1 511.0 MiB  14.8 MiB 496.1 MiB    3% /var/lib/snapd/hostfs/boot/efi
        /dev/mapper/sda 820.5 GiB 722.6 GiB  98.0 GiB   88% /var/lib/snapd/hostfs/Data
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /var/tmp
        /dev/mapper/sda 820.5 GiB 722.6 GiB  98.0 GiB   88% /run/timeshift/backup
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /usr/lib/modules
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /usr/lib/firmware
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /usr/src
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /var/log
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /media
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /mnt
            /dev/loop18  32.4 MiB  32.4 MiB       0 B  100% /usr/lib/snapd
/dev/mapper/vgmint-root 231.5 GiB  97.1 GiB 134.5 GiB   42% /snap

________________________________

**Comment by dundee** [comment]
Interesting, it's somehow connected with the first big letter in `Data`, but not sure yet why.

**Comment by dundee** [comment]
I have debugged it and unfortunately it cannot be solved, it's a feature of how snap filesystem works. 

When your current working directory is on a non primary drive, snap alters the system call to get absolute path of cwd and returns `/var/lib/snapd/void` instead.

You may use `gdu /Data` or `gdu -d`.
