### ISSUE TITLE
json file additions

### ISSUE THREAD

**Issue by keith6014** [dundee/gdu#91]
Can you please add if a file is hard/soft link in the json content?

**Comment by daniejstriata** [comment]
What if we keep the output of -o compatible but add a new option that can be customised depending on what values you want populated in the export?

`gdu --jout`
or
`gdu --jout=name,size,adate`

**Comment by dundee** [comment]
What should be done:
* if the File item has Flag `H`, add `"ino":XXX,"hlnkc":true` to the output buffer in `pkg/analyze/encode.go:59`
* XXX (the inode number) is stored as Mli (MultiLinkInode) on the File item
* add reading `ino` and `hlnkc` to `report/import.go`
